[tool.poetry]
name = "poetry2nix-install-ffmpeg-python"
version = "0.1.0"
description = ""
authors = ["Michael Noronha <michaeltnoronha@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
ffmpeg-python = "^0.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
